name: Trigger Release

on:
  push:
    branches:
      - main

jobs:
  trigger:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.PSAAS_PAT }}
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: 'WISE-Developers',
            repo: 'REDapp',
            workflow_id: 'maven-publish.yml',
            ref: 'main'
          })
    - uses: actions/github-script@v6
      name: Build WISE Builder
      with:
        github-token: ${{ secrets.PSAAS_PAT }}
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: 'WISE-Developers',
            repo: 'WISE_Builder_Component',
            workflow_id: 'maven-publish.yml',
            ref: 'main'
          })
    - uses: actions/github-script@v6
      name: Build WISE Manager
      with:
        github-token: ${{ secrets.PSAAS_PAT }}
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: 'WISE-Developers',
            repo: 'WISE_Manager_Component',
            workflow_id: 'maven-publish.yml',
            ref: 'main'
          })
    - uses: actions/github-script@v6
      name: Build WISE
      with:
        github-token: ${{ secrets.PSAAS_PAT }}
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: 'WISE-Developers',
            repo: 'WISE_Application',
            workflow_id: 'cmake.yml',
            ref: 'main'
          })
